name: Github Actions with CDK

on:
  push:
    branches: [ github-actions-aws ]
  pull_request:
    branches: [ github-actions-aws ]

jobs:
  aws_cdk:
    runs-on: ubuntu-latest
    steps:

      - name: cdk diff
        uses: youyo/aws-cdk-github-actions@v2
        with:
          cdk_subcommand: 'diff'
          actions_comment: true
        env:
          AWS_ACCESS_KEY_ID: 'AKIA47AZRCBYXXAITMPS'
          AWS_SECRET_ACCESS_KEY: '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'
          AWS_DEFAULT_REGION: 'eu-west-2'