name: AWS Login

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  build:
    runs-on: [self-hosted, macOS, X64]

    steps:
      - uses: actions/checkout@v3

      - name: demo workflow job
        run: echo This is a demo start workflow
