name: myPipe
on: 
  push:
    branches:
    - 'gh-pages'
jobs:
  runs-on: ubuntu-22.04
  steps:
  - uses: actions/checkout@v2
  - name: Write a multi-line message
    run: |
      echo This demo file shows a 
      echo very basic and easy-to-understand workflow.
